version: '3.1'

services:
  adminer:
    image: adminer
    ports:
      - "8090:8080"
    restart: 'no'
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: jLibrary
    ports:
      - "5432:5432"
    restart: 'no'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: