spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jLibrary
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.hibernate: ERROR
